# Generated by Django 5.0.1 on 2024-01-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_completed_todo_list_profile_regular_todo_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
