# Generated by Django 5.0.1 on 2024-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_todo_list',
            name='task_types',
            field=models.CharField(blank=True, choices=[('R', 'Regular'), ('U', 'Urgent')], max_length=50, null=True),
        ),
    ]
