# Generated by Django 4.2.7 on 2023-11-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
