# Generated by Django 5.0.1 on 2024-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_completed_todo_list_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_todo_list',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
