# Generated by Django 5.0.1 on 2024-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_completed_todo_list_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_todo_list',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
